// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'errors.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> addInventoryCategory(
        {required String name,
        String? parentId,
        required int sortOrder,
        required bool isPreset}) =>
    RustLib.instance.api.crateApiInventoryCategoriesAddInventoryCategory(
        name: name,
        parentId: parentId,
        sortOrder: sortOrder,
        isPreset: isPreset);

Future<List<InventoryCategory>> getInventoryCategories() =>
    RustLib.instance.api.crateApiInventoryCategoriesGetInventoryCategories();

Future<void> updateInventoryCategory(
        {required String id,
        required String name,
        String? parentId,
        required int sortOrder}) =>
    RustLib.instance.api.crateApiInventoryCategoriesUpdateInventoryCategory(
        id: id, name: name, parentId: parentId, sortOrder: sortOrder);

Future<void> deleteInventoryCategory({required String id}) =>
    RustLib.instance.api
        .crateApiInventoryCategoriesDeleteInventoryCategory(id: id);

Future<void> ensureInventoryCategory(
        {required String parentName, String? subName}) =>
    RustLib.instance.api.crateApiInventoryCategoriesEnsureInventoryCategory(
        parentName: parentName, subName: subName);

Future<void> batchUpdateInventoryCategory(
        {required List<String> ids, required String category}) =>
    RustLib.instance.api
        .crateApiInventoryCategoriesBatchUpdateInventoryCategory(
            ids: ids, category: category);
