// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'errors.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 保存新增囤货的草稿 (JSON 格式)
Future<void> saveInventoryDraft({required String jsonData}) =>
    RustLib.instance.api
        .crateApiInventoryDraftsSaveInventoryDraft(jsonData: jsonData);

/// 获取新增囤货的草稿
Future<String?> getInventoryDraft() =>
    RustLib.instance.api.crateApiInventoryDraftsGetInventoryDraft();

/// 清除新增囤货的草稿
Future<void> clearInventoryDraft() =>
    RustLib.instance.api.crateApiInventoryDraftsClearInventoryDraft();
