// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'errors.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> addInventoryItem(
        {required String name,
        required String category,
        required PlatformInt64 purchaseDate,
        required PlatformInt64 expirationDate,
        required double cost,
        String? imagePath}) =>
    RustLib.instance.api.crateApiInventoryItemsAddInventoryItem(
        name: name,
        category: category,
        purchaseDate: purchaseDate,
        expirationDate: expirationDate,
        cost: cost,
        imagePath: imagePath);

Future<void> updateInventoryItem(
        {required String id,
        required String name,
        required String category,
        required PlatformInt64 purchaseDate,
        required PlatformInt64 expirationDate,
        required double cost,
        String? imagePath}) =>
    RustLib.instance.api.crateApiInventoryItemsUpdateInventoryItem(
        id: id,
        name: name,
        category: category,
        purchaseDate: purchaseDate,
        expirationDate: expirationDate,
        cost: cost,
        imagePath: imagePath);

Future<List<InventoryItem>> getActiveInventoryItems() =>
    RustLib.instance.api.crateApiInventoryItemsGetActiveInventoryItems();

Future<List<GroupedInventoryItems>> searchAndGroupInventoryItems(
        {required String query}) =>
    RustLib.instance.api
        .crateApiInventoryItemsSearchAndGroupInventoryItems(query: query);

Future<void> deleteInventoryItem({required String id}) =>
    RustLib.instance.api.crateApiInventoryItemsDeleteInventoryItem(id: id);

Future<void> batchDeleteInventoryItems({required List<String> ids}) =>
    RustLib.instance.api
        .crateApiInventoryItemsBatchDeleteInventoryItems(ids: ids);
