// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'errors.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AccountOverviewStats {
  final double totalYear;
  final double totalQuarter;
  final double totalMonth;
  final double totalDay;
  final List<CategoryCostStat> categoryStats;

  const AccountOverviewStats({
    required this.totalYear,
    required this.totalQuarter,
    required this.totalMonth,
    required this.totalDay,
    required this.categoryStats,
  });

  @override
  int get hashCode =>
      totalYear.hashCode ^
      totalQuarter.hashCode ^
      totalMonth.hashCode ^
      totalDay.hashCode ^
      categoryStats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountOverviewStats &&
          runtimeType == other.runtimeType &&
          totalYear == other.totalYear &&
          totalQuarter == other.totalQuarter &&
          totalMonth == other.totalMonth &&
          totalDay == other.totalDay &&
          categoryStats == other.categoryStats;
}

class CategoryCostStat {
  final String name;
  final double totalCost;
  final double percentage;

  const CategoryCostStat({
    required this.name,
    required this.totalCost,
    required this.percentage,
  });

  @override
  int get hashCode => name.hashCode ^ totalCost.hashCode ^ percentage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryCostStat &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          totalCost == other.totalCost &&
          percentage == other.percentage;
}

class CategoryStat {
  final String name;
  final int count;

  const CategoryStat({
    required this.name,
    required this.count,
  });

  @override
  int get hashCode => name.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryStat &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          count == other.count;
}

class CreateItemPayload {
  final String name;
  final String category;
  final PlatformInt64 purchaseDate;
  final PlatformInt64 expirationDate;
  final double cost;
  final String? imagePath;

  const CreateItemPayload({
    required this.name,
    required this.category,
    required this.purchaseDate,
    required this.expirationDate,
    required this.cost,
    this.imagePath,
  });

  Future<(String, String, PlatformInt64, PlatformInt64, double, String?)>
      validateAndSanitize() => RustLib.instance.api
              .crateApiInventoryModelsCreateItemPayloadValidateAndSanitize(
            that: this,
          );

  @override
  int get hashCode =>
      name.hashCode ^
      category.hashCode ^
      purchaseDate.hashCode ^
      expirationDate.hashCode ^
      cost.hashCode ^
      imagePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateItemPayload &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          category == other.category &&
          purchaseDate == other.purchaseDate &&
          expirationDate == other.expirationDate &&
          cost == other.cost &&
          imagePath == other.imagePath;
}

class GroupedInventoryItems {
  final String category;
  final PlatformInt64 count;
  final List<InventoryItem> items;

  const GroupedInventoryItems({
    required this.category,
    required this.count,
    required this.items,
  });

  @override
  int get hashCode => category.hashCode ^ count.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupedInventoryItems &&
          runtimeType == other.runtimeType &&
          category == other.category &&
          count == other.count &&
          items == other.items;
}

class InventoryCategory {
  final String id;
  final String name;
  final String? parentId;
  final int sortOrder;
  final bool isPreset;

  const InventoryCategory({
    required this.id,
    required this.name,
    this.parentId,
    required this.sortOrder,
    required this.isPreset,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      parentId.hashCode ^
      sortOrder.hashCode ^
      isPreset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InventoryCategory &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          sortOrder == other.sortOrder &&
          isPreset == other.isPreset;
}

class InventoryItem {
  final String id;
  final String name;
  final String category;
  final PlatformInt64 purchaseDate;
  final PlatformInt64 expirationDate;
  final double cost;
  final String status;
  final String? imagePath;
  final PlatformInt64 daysOwned;
  final PlatformInt64 daysLeft;
  final double dailyCost;

  const InventoryItem({
    required this.id,
    required this.name,
    required this.category,
    required this.purchaseDate,
    required this.expirationDate,
    required this.cost,
    required this.status,
    this.imagePath,
    required this.daysOwned,
    required this.daysLeft,
    required this.dailyCost,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      category.hashCode ^
      purchaseDate.hashCode ^
      expirationDate.hashCode ^
      cost.hashCode ^
      status.hashCode ^
      imagePath.hashCode ^
      daysOwned.hashCode ^
      daysLeft.hashCode ^
      dailyCost.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InventoryItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          category == other.category &&
          purchaseDate == other.purchaseDate &&
          expirationDate == other.expirationDate &&
          cost == other.cost &&
          status == other.status &&
          imagePath == other.imagePath &&
          daysOwned == other.daysOwned &&
          daysLeft == other.daysLeft &&
          dailyCost == other.dailyCost;
}

class InventorySearchQuery {
  final String? query;
  final String? category;
  final PlatformInt64? startDate;
  final PlatformInt64? endDate;
  final double? minCost;
  final double? maxCost;

  const InventorySearchQuery({
    this.query,
    this.category,
    this.startDate,
    this.endDate,
    this.minCost,
    this.maxCost,
  });

  @override
  int get hashCode =>
      query.hashCode ^
      category.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      minCost.hashCode ^
      maxCost.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InventorySearchQuery &&
          runtimeType == other.runtimeType &&
          query == other.query &&
          category == other.category &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          minCost == other.minCost &&
          maxCost == other.maxCost;
}

class MonthGroupedItems {
  final String month;
  final double totalCost;
  final List<InventoryItem> items;

  const MonthGroupedItems({
    required this.month,
    required this.totalCost,
    required this.items,
  });

  @override
  int get hashCode => month.hashCode ^ totalCost.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MonthGroupedItems &&
          runtimeType == other.runtimeType &&
          month == other.month &&
          totalCost == other.totalCost &&
          items == other.items;
}
