// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/debug.dart';
import 'api/inventory.dart';
import 'api/pet.dart';
import 'api/system.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 615811322;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_petlove',
    ioDirectory: '../core/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiInventoryAddInventoryItem(
      {required String name,
      required String category,
      required PlatformInt64 purchaseDate,
      required PlatformInt64 expirationDate,
      required double cost,
      String? imagePath});

  Future<UpdateInfo> crateApiSystemCheckAppUpdate(
      {required String currentVersion});

  Future<List<PetStatusLog>> crateApiPetCheckPetConflicts(
      {required String petId, required String dataType});

  Future<void> crateApiInventoryClearInventoryDraft();

  Future<void> crateApiInventoryDeleteInventoryItem({required String id});

  Future<DbQueryResult> crateApiDebugExecuteDebugSql({required String sql});

  Future<String> crateApiSystemExportDiagnosticLogs();

  Future<List<InventoryItem>> crateApiInventoryGetActiveInventoryItems();

  Future<String?> crateApiSystemGetAppSetting({required String key});

  Future<List<CategoryCostStat>> crateApiInventoryGetCategoryCostStats();

  Future<List<CategoryStat>> crateApiInventoryGetCategoryStats();

  Future<String?> crateApiInventoryGetInventoryDraft();

  Future<void> crateApiSystemInitSystem({required String dbPath});

  Future<List<String>> crateApiDebugListTables();

  Future<void> crateApiPetResolvePetConflict(
      {required String petId,
      required String dataType,
      String? logIdToKeep,
      String? mergedValue});

  Future<void> crateApiInventorySaveInventoryDraft({required String jsonData});

  Future<void> crateApiSystemSetAppSetting(
      {required String key, required String value});

  Future<void> crateApiSystemTrackTelemetryEvent(
      {required String eventName, required String paramsJson});

  Future<void> crateApiInventoryUpdateInventoryItem(
      {required String id,
      required String name,
      required String category,
      required PlatformInt64 purchaseDate,
      required PlatformInt64 expirationDate,
      required double cost,
      String? imagePath});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiInventoryAddInventoryItem(
      {required String name,
      required String category,
      required PlatformInt64 purchaseDate,
      required PlatformInt64 expirationDate,
      required double cost,
      String? imagePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(category, serializer);
        sse_encode_i_64(purchaseDate, serializer);
        sse_encode_i_64(expirationDate, serializer);
        sse_encode_f_64(cost, serializer);
        sse_encode_opt_String(imagePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInventoryAddInventoryItemConstMeta,
      argValues: [
        name,
        category,
        purchaseDate,
        expirationDate,
        cost,
        imagePath
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInventoryAddInventoryItemConstMeta =>
      const TaskConstMeta(
        debugName: "add_inventory_item",
        argNames: [
          "name",
          "category",
          "purchaseDate",
          "expirationDate",
          "cost",
          "imagePath"
        ],
      );

  @override
  Future<UpdateInfo> crateApiSystemCheckAppUpdate(
      {required String currentVersion}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(currentVersion, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_update_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSystemCheckAppUpdateConstMeta,
      argValues: [currentVersion],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSystemCheckAppUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "check_app_update",
        argNames: ["currentVersion"],
      );

  @override
  Future<List<PetStatusLog>> crateApiPetCheckPetConflicts(
      {required String petId, required String dataType}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(petId, serializer);
        sse_encode_String(dataType, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_pet_status_log,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPetCheckPetConflictsConstMeta,
      argValues: [petId, dataType],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPetCheckPetConflictsConstMeta =>
      const TaskConstMeta(
        debugName: "check_pet_conflicts",
        argNames: ["petId", "dataType"],
      );

  @override
  Future<void> crateApiInventoryClearInventoryDraft() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInventoryClearInventoryDraftConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInventoryClearInventoryDraftConstMeta =>
      const TaskConstMeta(
        debugName: "clear_inventory_draft",
        argNames: [],
      );

  @override
  Future<void> crateApiInventoryDeleteInventoryItem({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInventoryDeleteInventoryItemConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInventoryDeleteInventoryItemConstMeta =>
      const TaskConstMeta(
        debugName: "delete_inventory_item",
        argNames: ["id"],
      );

  @override
  Future<DbQueryResult> crateApiDebugExecuteDebugSql({required String sql}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sql, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_db_query_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDebugExecuteDebugSqlConstMeta,
      argValues: [sql],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDebugExecuteDebugSqlConstMeta =>
      const TaskConstMeta(
        debugName: "execute_debug_sql",
        argNames: ["sql"],
      );

  @override
  Future<String> crateApiSystemExportDiagnosticLogs() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSystemExportDiagnosticLogsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSystemExportDiagnosticLogsConstMeta =>
      const TaskConstMeta(
        debugName: "export_diagnostic_logs",
        argNames: [],
      );

  @override
  Future<List<InventoryItem>> crateApiInventoryGetActiveInventoryItems() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_inventory_item,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInventoryGetActiveInventoryItemsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInventoryGetActiveInventoryItemsConstMeta =>
      const TaskConstMeta(
        debugName: "get_active_inventory_items",
        argNames: [],
      );

  @override
  Future<String?> crateApiSystemGetAppSetting({required String key}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(key, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSystemGetAppSettingConstMeta,
      argValues: [key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSystemGetAppSettingConstMeta =>
      const TaskConstMeta(
        debugName: "get_app_setting",
        argNames: ["key"],
      );

  @override
  Future<List<CategoryCostStat>> crateApiInventoryGetCategoryCostStats() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_category_cost_stat,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInventoryGetCategoryCostStatsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInventoryGetCategoryCostStatsConstMeta =>
      const TaskConstMeta(
        debugName: "get_category_cost_stats",
        argNames: [],
      );

  @override
  Future<List<CategoryStat>> crateApiInventoryGetCategoryStats() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_category_stat,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInventoryGetCategoryStatsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInventoryGetCategoryStatsConstMeta =>
      const TaskConstMeta(
        debugName: "get_category_stats",
        argNames: [],
      );

  @override
  Future<String?> crateApiInventoryGetInventoryDraft() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInventoryGetInventoryDraftConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInventoryGetInventoryDraftConstMeta =>
      const TaskConstMeta(
        debugName: "get_inventory_draft",
        argNames: [],
      );

  @override
  Future<void> crateApiSystemInitSystem({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSystemInitSystemConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSystemInitSystemConstMeta => const TaskConstMeta(
        debugName: "init_system",
        argNames: ["dbPath"],
      );

  @override
  Future<List<String>> crateApiDebugListTables() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDebugListTablesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDebugListTablesConstMeta => const TaskConstMeta(
        debugName: "list_tables",
        argNames: [],
      );

  @override
  Future<void> crateApiPetResolvePetConflict(
      {required String petId,
      required String dataType,
      String? logIdToKeep,
      String? mergedValue}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(petId, serializer);
        sse_encode_String(dataType, serializer);
        sse_encode_opt_String(logIdToKeep, serializer);
        sse_encode_opt_String(mergedValue, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiPetResolvePetConflictConstMeta,
      argValues: [petId, dataType, logIdToKeep, mergedValue],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPetResolvePetConflictConstMeta =>
      const TaskConstMeta(
        debugName: "resolve_pet_conflict",
        argNames: ["petId", "dataType", "logIdToKeep", "mergedValue"],
      );

  @override
  Future<void> crateApiInventorySaveInventoryDraft({required String jsonData}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(jsonData, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInventorySaveInventoryDraftConstMeta,
      argValues: [jsonData],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInventorySaveInventoryDraftConstMeta =>
      const TaskConstMeta(
        debugName: "save_inventory_draft",
        argNames: ["jsonData"],
      );

  @override
  Future<void> crateApiSystemSetAppSetting(
      {required String key, required String value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(key, serializer);
        sse_encode_String(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSystemSetAppSettingConstMeta,
      argValues: [key, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSystemSetAppSettingConstMeta =>
      const TaskConstMeta(
        debugName: "set_app_setting",
        argNames: ["key", "value"],
      );

  @override
  Future<void> crateApiSystemTrackTelemetryEvent(
      {required String eventName, required String paramsJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(eventName, serializer);
        sse_encode_String(paramsJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSystemTrackTelemetryEventConstMeta,
      argValues: [eventName, paramsJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSystemTrackTelemetryEventConstMeta =>
      const TaskConstMeta(
        debugName: "track_telemetry_event",
        argNames: ["eventName", "paramsJson"],
      );

  @override
  Future<void> crateApiInventoryUpdateInventoryItem(
      {required String id,
      required String name,
      required String category,
      required PlatformInt64 purchaseDate,
      required PlatformInt64 expirationDate,
      required double cost,
      String? imagePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(category, serializer);
        sse_encode_i_64(purchaseDate, serializer);
        sse_encode_i_64(expirationDate, serializer);
        sse_encode_f_64(cost, serializer);
        sse_encode_opt_String(imagePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInventoryUpdateInventoryItemConstMeta,
      argValues: [
        id,
        name,
        category,
        purchaseDate,
        expirationDate,
        cost,
        imagePath
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInventoryUpdateInventoryItemConstMeta =>
      const TaskConstMeta(
        debugName: "update_inventory_item",
        argNames: [
          "id",
          "name",
          "category",
          "purchaseDate",
          "expirationDate",
          "cost",
          "imagePath"
        ],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CategoryCostStat dco_decode_category_cost_stat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CategoryCostStat(
      name: dco_decode_String(arr[0]),
      totalCost: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  CategoryStat dco_decode_category_stat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CategoryStat(
      name: dco_decode_String(arr[0]),
      count: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  DbQueryResult dco_decode_db_query_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DbQueryResult(
      columns: dco_decode_list_String(arr[0]),
      rows: dco_decode_list_list_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  InventoryItem dco_decode_inventory_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return InventoryItem(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      category: dco_decode_String(arr[2]),
      purchaseDate: dco_decode_i_64(arr[3]),
      expirationDate: dco_decode_i_64(arr[4]),
      cost: dco_decode_f_64(arr[5]),
      status: dco_decode_String(arr[6]),
      imagePath: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CategoryCostStat> dco_decode_list_category_cost_stat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_category_cost_stat).toList();
  }

  @protected
  List<CategoryStat> dco_decode_list_category_stat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_category_stat).toList();
  }

  @protected
  List<InventoryItem> dco_decode_list_inventory_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_inventory_item).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  List<PetStatusLog> dco_decode_list_pet_status_log(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pet_status_log).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PetStatusLog dco_decode_pet_status_log(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PetStatusLog(
      id: dco_decode_String(arr[0]),
      petId: dco_decode_String(arr[1]),
      dataType: dco_decode_String(arr[2]),
      dataValue: dco_decode_String(arr[3]),
      createdBy: dco_decode_String(arr[4]),
      clientTimestamp: dco_decode_i_64(arr[5]),
      status: dco_decode_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpdateInfo dco_decode_update_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return UpdateInfo(
      hasUpdate: dco_decode_bool(arr[0]),
      isForced: dco_decode_bool(arr[1]),
      latestVersion: dco_decode_String(arr[2]),
      changelog: dco_decode_String(arr[3]),
      downloadUrl: dco_decode_String(arr[4]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CategoryCostStat sse_decode_category_cost_stat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_totalCost = sse_decode_f_64(deserializer);
    return CategoryCostStat(name: var_name, totalCost: var_totalCost);
  }

  @protected
  CategoryStat sse_decode_category_stat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_count = sse_decode_u_32(deserializer);
    return CategoryStat(name: var_name, count: var_count);
  }

  @protected
  DbQueryResult sse_decode_db_query_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_columns = sse_decode_list_String(deserializer);
    var var_rows = sse_decode_list_list_String(deserializer);
    return DbQueryResult(columns: var_columns, rows: var_rows);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  InventoryItem sse_decode_inventory_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_purchaseDate = sse_decode_i_64(deserializer);
    var var_expirationDate = sse_decode_i_64(deserializer);
    var var_cost = sse_decode_f_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_imagePath = sse_decode_opt_String(deserializer);
    return InventoryItem(
        id: var_id,
        name: var_name,
        category: var_category,
        purchaseDate: var_purchaseDate,
        expirationDate: var_expirationDate,
        cost: var_cost,
        status: var_status,
        imagePath: var_imagePath);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CategoryCostStat> sse_decode_list_category_cost_stat(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CategoryCostStat>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_category_cost_stat(deserializer));
    }
    return ans_;
  }

  @protected
  List<CategoryStat> sse_decode_list_category_stat(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CategoryStat>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_category_stat(deserializer));
    }
    return ans_;
  }

  @protected
  List<InventoryItem> sse_decode_list_inventory_item(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InventoryItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_inventory_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<PetStatusLog> sse_decode_list_pet_status_log(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PetStatusLog>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pet_status_log(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PetStatusLog sse_decode_pet_status_log(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_petId = sse_decode_String(deserializer);
    var var_dataType = sse_decode_String(deserializer);
    var var_dataValue = sse_decode_String(deserializer);
    var var_createdBy = sse_decode_String(deserializer);
    var var_clientTimestamp = sse_decode_i_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    return PetStatusLog(
        id: var_id,
        petId: var_petId,
        dataType: var_dataType,
        dataValue: var_dataValue,
        createdBy: var_createdBy,
        clientTimestamp: var_clientTimestamp,
        status: var_status);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpdateInfo sse_decode_update_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hasUpdate = sse_decode_bool(deserializer);
    var var_isForced = sse_decode_bool(deserializer);
    var var_latestVersion = sse_decode_String(deserializer);
    var var_changelog = sse_decode_String(deserializer);
    var var_downloadUrl = sse_decode_String(deserializer);
    return UpdateInfo(
        hasUpdate: var_hasUpdate,
        isForced: var_isForced,
        latestVersion: var_latestVersion,
        changelog: var_changelog,
        downloadUrl: var_downloadUrl);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_category_cost_stat(
      CategoryCostStat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_f_64(self.totalCost, serializer);
  }

  @protected
  void sse_encode_category_stat(CategoryStat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.count, serializer);
  }

  @protected
  void sse_encode_db_query_result(
      DbQueryResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.columns, serializer);
    sse_encode_list_list_String(self.rows, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_inventory_item(InventoryItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_i_64(self.purchaseDate, serializer);
    sse_encode_i_64(self.expirationDate, serializer);
    sse_encode_f_64(self.cost, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.imagePath, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_category_cost_stat(
      List<CategoryCostStat> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_category_cost_stat(item, serializer);
    }
  }

  @protected
  void sse_encode_list_category_stat(
      List<CategoryStat> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_category_stat(item, serializer);
    }
  }

  @protected
  void sse_encode_list_inventory_item(
      List<InventoryItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_inventory_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
      List<List<String>> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pet_status_log(
      List<PetStatusLog> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pet_status_log(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_pet_status_log(PetStatusLog self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.petId, serializer);
    sse_encode_String(self.dataType, serializer);
    sse_encode_String(self.dataValue, serializer);
    sse_encode_String(self.createdBy, serializer);
    sse_encode_i_64(self.clientTimestamp, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_update_info(UpdateInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.hasUpdate, serializer);
    sse_encode_bool(self.isForced, serializer);
    sse_encode_String(self.latestVersion, serializer);
    sse_encode_String(self.changelog, serializer);
    sse_encode_String(self.downloadUrl, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
