// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<String> addInventoryItem(
        {required String name,
        required String category,
        required PlatformInt64 purchaseDate,
        required PlatformInt64 expirationDate,
        required double cost,
        String? imagePath}) =>
    RustLib.instance.api.crateApiInventoryAddInventoryItem(
        name: name,
        category: category,
        purchaseDate: purchaseDate,
        expirationDate: expirationDate,
        cost: cost,
        imagePath: imagePath);

Future<List<InventoryItem>> getActiveInventoryItems() =>
    RustLib.instance.api.crateApiInventoryGetActiveInventoryItems();

Future<void> deleteInventoryItem({required String id}) =>
    RustLib.instance.api.crateApiInventoryDeleteInventoryItem(id: id);

Future<void> updateInventoryItem(
        {required String id,
        required String name,
        required String category,
        required PlatformInt64 purchaseDate,
        required PlatformInt64 expirationDate,
        required double cost,
        String? imagePath}) =>
    RustLib.instance.api.crateApiInventoryUpdateInventoryItem(
        id: id,
        name: name,
        category: category,
        purchaseDate: purchaseDate,
        expirationDate: expirationDate,
        cost: cost,
        imagePath: imagePath);

class InventoryItem {
  final String id;
  final String name;
  final String category;
  final PlatformInt64 purchaseDate;
  final PlatformInt64 expirationDate;
  final double cost;
  final String status;
  final String? imagePath;

  const InventoryItem({
    required this.id,
    required this.name,
    required this.category,
    required this.purchaseDate,
    required this.expirationDate,
    required this.cost,
    required this.status,
    this.imagePath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      category.hashCode ^
      purchaseDate.hashCode ^
      expirationDate.hashCode ^
      cost.hashCode ^
      status.hashCode ^
      imagePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InventoryItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          category == other.category &&
          purchaseDate == other.purchaseDate &&
          expirationDate == other.expirationDate &&
          cost == other.cost &&
          status == other.status &&
          imagePath == other.imagePath;
}
