// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 检查指定宠物模块的未决冲突
///
/// 查找同一 `pet_id` 和 `data_type` 下，状态为 'active' 的多条记录。
Future<List<PetStatusLog>> checkPetConflicts(
        {required String petId, required String dataType}) =>
    RustLib.instance.api
        .crateApiPetCheckPetConflicts(petId: petId, dataType: dataType);

/// 解决冲突并保存最终结果
///
/// `log_id_to_keep`: 若选择保留某条冲突记录，则传其 ID
/// `merged_value`: 若选择输入全新合并值，则传合并后的值
Future<void> resolvePetConflict(
        {required String petId,
        required String dataType,
        String? logIdToKeep,
        String? mergedValue}) =>
    RustLib.instance.api.crateApiPetResolvePetConflict(
        petId: petId,
        dataType: dataType,
        logIdToKeep: logIdToKeep,
        mergedValue: mergedValue);

class PetStatusLog {
  final String id;
  final String petId;
  final String dataType;
  final String dataValue;
  final String createdBy;
  final PlatformInt64 clientTimestamp;
  final String status;

  const PetStatusLog({
    required this.id,
    required this.petId,
    required this.dataType,
    required this.dataValue,
    required this.createdBy,
    required this.clientTimestamp,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      petId.hashCode ^
      dataType.hashCode ^
      dataValue.hashCode ^
      createdBy.hashCode ^
      clientTimestamp.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PetStatusLog &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          petId == other.petId &&
          dataType == other.dataType &&
          dataValue == other.dataValue &&
          createdBy == other.createdBy &&
          clientTimestamp == other.clientTimestamp &&
          status == other.status;
}
