// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 初始化系统环境，包括数据库路径
Future<void> initSystem({required String dbPath}) =>
    RustLib.instance.api.crateApiSystemInitSystem(dbPath: dbPath);

/// 保存应用设置 (KV)
Future<void> setAppSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiSystemSetAppSetting(key: key, value: value);

/// 获取应用设置 (KV)
Future<String?> getAppSetting({required String key}) =>
    RustLib.instance.api.crateApiSystemGetAppSetting(key: key);

/// 导出排查日志文件文本内容
Future<String> exportDiagnosticLogs() =>
    RustLib.instance.api.crateApiSystemExportDiagnosticLogs();

/// 触发数据埋点事件 (Telemetry)
Future<void> trackTelemetryEvent(
        {required String eventName, required String paramsJson}) =>
    RustLib.instance.api.crateApiSystemTrackTelemetryEvent(
        eventName: eventName, paramsJson: paramsJson);

/// 校验 App 在线更新 (OTA)
Future<UpdateInfo> checkAppUpdate({required String currentVersion}) =>
    RustLib.instance.api
        .crateApiSystemCheckAppUpdate(currentVersion: currentVersion);

class UpdateInfo {
  final bool hasUpdate;
  final bool isForced;
  final String latestVersion;
  final String changelog;
  final String downloadUrl;

  const UpdateInfo({
    required this.hasUpdate,
    required this.isForced,
    required this.latestVersion,
    required this.changelog,
    required this.downloadUrl,
  });

  @override
  int get hashCode =>
      hasUpdate.hashCode ^
      isForced.hashCode ^
      latestVersion.hashCode ^
      changelog.hashCode ^
      downloadUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateInfo &&
          runtimeType == other.runtimeType &&
          hasUpdate == other.hasUpdate &&
          isForced == other.isForced &&
          latestVersion == other.latestVersion &&
          changelog == other.changelog &&
          downloadUrl == other.downloadUrl;
}
